# Generated by Django 6.0.3 on 2026-06-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='معرف الجلسة')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جلسة شات',
                'verbose_name_plural': 'جلسات الشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('category', models.CharField(choices=[('general', 'عام'), ('architecture', 'هيكل المشروع'), ('models', 'الموديلات'), ('views', 'الViews'), ('urls', 'الروابط'), ('setup', 'التشغيل والإعداد'), ('accounts', 'المستخدمين والصلاحيات'), ('students', 'الطلاب'), ('courses', 'الدورات'), ('registrations', 'التسجيلات'), ('finance', 'المالية'), ('offers', 'العروض'), ('messaging', 'المراسلة'), ('notifications', 'الإشعارات'), ('reports', 'التقارير'), ('frontend', 'الواجهة الأمامية')], default='general', max_length=50, verbose_name='التصنيف')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='ملف المصدر')),
                ('keywords', models.TextField(blank=True, verbose_name='الكلمات المفتاحية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مقطع معرفة',
                'verbose_name_plural': 'مقاطع المعرفة',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'المستخدم'), ('assistant', 'المساعد')], max_length=20, verbose_name='الدور')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='المصادر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='project_assistant.chatsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'رسالة شات',
                'verbose_name_plural': 'رسائل الشات',
                'ordering': ['created_at'],
            },
        ),
    ]
