# Generated by Django 6.0.3 on 2026-04-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('second_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الثاني')),
                ('third_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الثالث')),
                ('forth_name', models.CharField(max_length=100, verbose_name='الاسم الرابع')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='المحمول')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='التليفون')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='الجنسية')),
                ('identity_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الهوية')),
                ('identity_location', models.CharField(blank=True, max_length=255, verbose_name='مكان إصدار الهوية')),
                ('identity_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إصدار الهوية')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('birth_location', models.CharField(blank=True, max_length=255, verbose_name='مكان الميلاد')),
                ('qualification', models.CharField(blank=True, max_length=255, verbose_name='المؤهل')),
                ('photo', models.TextField(blank=True, verbose_name='الصورة (Base64)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'جهة اتصال',
                'verbose_name_plural': 'جهات الاتصال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='students.contact', verbose_name='جهة الاتصال')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['-created_at'],
            },
        ),
    ]
