# Generated by Django 6.0.3 on 2026-04-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('مبتدئ', 'مبتدئ'), ('متوسط', 'متوسط'), ('متقدم', 'متقدم')], default='مبتدئ', max_length=20, verbose_name='المستوى'),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'البريد الإلكتروني'), ('whatsapp', 'واتساب'), ('app', 'إشعار التطبيق')], default='whatsapp', max_length=20, verbose_name='طريقة التواصل المفضلة'),
        ),
    ]
