# Generated by Django 6.0.3 on 2026-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_level_student_preferred_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='forth_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='الاسم الرابع'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='المحمول'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('مبتدئ', 'مبتدئ'), ('متوسط', 'متوسط'), ('متقدم', 'متقدم')], db_index=True, default='مبتدئ', max_length=20, verbose_name='المستوى'),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'البريد الإلكتروني'), ('whatsapp', 'واتساب'), ('app', 'إشعار التطبيق')], db_index=True, default='whatsapp', max_length=20, verbose_name='طريقة التواصل المفضلة'),
        ),
    ]
