# Generated by Django 6.0.3 on 2026-05-10 15:00

from django.db import migrations
from django.utils.text import slugify


def fill_student_slugs(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all():
        if not student.slug:
            contact = student.contact
            full_name = ' '.join(filter(None, [contact.first_name, contact.second_name, contact.third_name, contact.forth_name])).strip()
            base = slugify(full_name or 'student', allow_unicode=True)
            slug = base
            counter = 1
            while Student.objects.filter(slug=slug).exclude(pk=student.pk).exists():
                slug = f"{base}-{counter}"
                counter += 1
            student.slug = slug
            student.save(update_fields=['slug'])


def reverse_fill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_slug'),
    ]

    operations = [
        migrations.RunPython(fill_student_slugs, reverse_fill),
    ]
