# Generated by Django 6.0.3 on 2026-05-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_fill_student_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, upload_to='contact_photos/', verbose_name='الصورة'),
        ),
    ]
