# Generated by Django 6.0.3 on 2026-06-18 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_branch_signature'),
        ('students', '0006_alter_contact_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.branch', verbose_name='الفرع'),
        ),
    ]
