# Generated by Django 6.0.3 on 2026-06-18 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_branch_signature'),
        ('students', '0007_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.branch', verbose_name='الفرع'),
        ),
    ]
