# Generated by Django 6.0.3 on 2026-04-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفرع')),
                ('sub_name', models.CharField(blank=True, max_length=255, verbose_name='الاسم الفرعي')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone1', models.CharField(blank=True, max_length=20, verbose_name='التليفون 1')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='التليفون 2')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرقم البريدي')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='المحمول')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='الفاكس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('commercial_registration', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('licence_code', models.CharField(blank=True, max_length=50, verbose_name='رقم الترخيص')),
                ('tax_code', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('logo', models.TextField(blank=True, verbose_name='الشعار (Base64)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('sub_name', models.CharField(blank=True, max_length=255, verbose_name='الاسم الفرعي')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('phone1', models.CharField(blank=True, max_length=20, verbose_name='التليفون 1')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='التليفون 2')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرقم البريدي')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='المحمول')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='الفاكس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('commercial_registration', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('tax_code', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('logo', models.TextField(blank=True, verbose_name='الشعار (Base64)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم التصنيف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تصنيف التخصص',
                'verbose_name_plural': 'تصنيفات التخصصات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم البنك')),
                ('account_number', models.CharField(max_length=100, verbose_name='رقم الحساب')),
                ('iban', models.CharField(blank=True, max_length=100, verbose_name='IBAN')),
                ('swift', models.CharField(blank=True, max_length=50, verbose_name='SWIFT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'بنك',
                'verbose_name_plural': 'البنوك',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.company', verbose_name='الشركة'),
        ),
    ]
