# Generated by Django 6.0.3 on 2026-05-09 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bank_branch_alter_branch_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsidiaries', to='core.company', verbose_name='الشركة الأم'),
        ),
    ]
