# Generated by Django 6.0.3 on 2026-05-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='parent',
        ),
    ]
