# Generated by Django 6.0.3 on 2026-05-09 18:15

from django.db import migrations
from django.utils.text import slugify


def fill_slugs(apps, schema_editor):
    Company = apps.get_model('core', 'Company')
    for company in Company.objects.all():
        if not company.slug:
            base_slug = slugify(company.name, allow_unicode=True)
            slug = base_slug
            counter = 1
            while Company.objects.filter(slug=slug).exclude(pk=company.pk).exists():
                slug = f'{base_slug}-{counter}'
                counter += 1
            company.slug = slug
            company.save(update_fields=['slug'])


def reverse_fill_slugs(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_slug'),
    ]

    operations = [
        migrations.RunPython(fill_slugs, reverse_fill_slugs),
    ]
