# Generated by Django 6.0.3 on 2026-05-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fill_company_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='الرابط المختصر'),
        ),
    ]
