# Generated by Django 6.0.3 on 2026-05-09 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_branch_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercategory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='core.branch', verbose_name='الفرع'),
        ),
    ]
