# Generated by Django 6.0.3 on 2026-05-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mastercategory_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='الرابط المختصر'),
        ),
    ]
