# Generated by Django 6.0.3 on 2026-05-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mastercategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, upload_to='branch_logos/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company_logos/', verbose_name='الشعار'),
        ),
    ]
