# Generated by Django 6.0.3 on 2026-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_branch_logo_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='signature',
            field=models.ImageField(blank=True, upload_to='branch_signatures/', verbose_name='التوقيع'),
        ),
    ]
