# Generated by Django 6.0.3 on 2026-06-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_branch_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(choices=[('SAR', 'ريال سعودي'), ('JOD', 'دينار أردني'), ('USD', 'دولار أمريكي'), ('EGP', 'جنيه مصري'), ('AED', 'درهم إماراتي')], default='SAR', max_length=3, verbose_name='العملة'),
        ),
    ]
