# Generated by Django 6.0.3 on 2026-06-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_company_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='offer_template',
            field=models.TextField(blank=True, verbose_name='نموذج وصف العرض'),
        ),
    ]
