# Generated by Django 6.0.3 on 2026-04-04 09:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('courses', '0001_initial'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillBuyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوع فاتورة شراء',
                'verbose_name_plural': 'أنواع فواتير الشراء',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveBigIntegerField(verbose_name='الكود')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('supplier', models.CharField(max_length=255, verbose_name='المورد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الضريبة')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصم')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل')),
                ('bill_buy_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.billbuytype', verbose_name='النوع')),
            ],
            options={
                'verbose_name': 'فاتورة شراء',
                'verbose_name_plural': 'فواتير الشراء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveBigIntegerField(verbose_name='الكود')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank', verbose_name='البنك')),
                ('last_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'إيداع',
                'verbose_name_plural': 'الإيداعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='الكود')),
                ('customer_name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('customer_identity_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الهوية')),
                ('customer_mobile', models.CharField(blank=True, max_length=20, verbose_name='جوال العميل')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد العميل')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('message_body', models.TextField(blank=True, verbose_name='نص الرسالة')),
                ('master_payment_type', models.CharField(choices=[('نقدي', 'نقدي'), ('تقسيط', 'تقسيط'), ('آجل', 'آجل')], default='نقدي', max_length=20, verbose_name='نوع الدفع')),
                ('master_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر')),
                ('master_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نسبة الخصم')),
                ('master_profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نسبة الربح')),
                ('master_credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ الائتمان')),
                ('send_email', models.BooleanField(default=True, verbose_name='إرسال بريد')),
                ('send_sms', models.BooleanField(default=True, verbose_name='إرسال SMS')),
                ('sms_body', models.TextField(blank=True, verbose_name='نص SMS')),
                ('message_sid', models.CharField(blank=True, max_length=255, verbose_name='معرف الرسالة')),
                ('registered', models.BooleanField(default=False, verbose_name='مسجل')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='courses.master', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
                'ordering': ['-created_at'],
                'unique_together': {('master', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('INCOMING', 'واردة'), ('OUTGOING', 'صادرة')], default='OUTGOING', max_length=20, verbose_name='نوع المكالمة')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='المدة (ثانية)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='finance.offer', verbose_name='العرض')),
            ],
            options={
                'verbose_name': 'مكالمة',
                'verbose_name_plural': 'المكالمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveBigIntegerField(verbose_name='الكود')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('amount_number', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ رقم')),
                ('amount_string', models.CharField(blank=True, max_length=500, verbose_name='المبلغ حروف')),
                ('type', models.CharField(choices=[('ايرادات اساسية', 'إيرادات أساسية'), ('ايرادات اخرى', 'إيرادات أخرى')], default='ايرادات اساسية', max_length=50, verbose_name='النوع')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي'), ('BANK', 'تحويل بنكي'), ('CHEQUE', 'شيك'), ('CARD', 'بطاقة ائتمان'), ('ONLINE', 'دفع إلكتروني')], default='CASH', max_length=20, verbose_name='طريقة الدفع')),
                ('payment_method_code', models.CharField(blank=True, max_length=100, verbose_name='كود الدفع')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='registrations.account', verbose_name='التسجيل')),
                ('last_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'سند قبض',
                'verbose_name_plural': 'سندات القبض',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveBigIntegerField(verbose_name='الكود')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('amount_number', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ رقم')),
                ('amount_string', models.CharField(blank=True, max_length=500, verbose_name='المبلغ حروف')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='اسم المستلم')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('payment_method', models.CharField(choices=[('CASH', 'نقدي'), ('BANK', 'تحويل بنكي'), ('CHEQUE', 'شيك'), ('CARD', 'بطاقة ائتمان'), ('ONLINE', 'دفع إلكتروني')], default='CASH', max_length=20, verbose_name='طريقة الدفع')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'سند صرف',
                'verbose_name_plural': 'سندات الصرف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveBigIntegerField(verbose_name='الكود')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank', verbose_name='البنك')),
                ('last_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'سحب',
                'verbose_name_plural': 'السحوبات',
                'ordering': ['-created_at'],
            },
        ),
    ]
