# Generated by Django 6.0.3 on 2026-05-07 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bank_branch_alter_branch_company'),
        ('courses', '0003_alter_course_code_alter_course_instructor_and_more'),
        ('finance', '0001_initial'),
        ('registrations', '0002_alter_account_code_alter_account_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billbuy',
            name='bill_buy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.billbuytype', verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='billbuy',
            name='code',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='billbuy',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='billbuy',
            name='supplier',
            field=models.CharField(db_index=True, max_length=255, verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='billbuytype',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='billbuytype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='call',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='finance.offer', verbose_name='العرض'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.bank', verbose_name='البنك'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='code',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.PositiveIntegerField(db_index=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='customer_mobile',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='جوال العميل'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='courses.master', verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='master_payment_type',
            field=models.CharField(choices=[('نقدي', 'نقدي'), ('تقسيط', 'تقسيط'), ('آجل', 'آجل')], db_index=True, default='نقدي', max_length=20, verbose_name='نوع الدفع'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='registered',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مسجل'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='registrations.account', verbose_name='التسجيل'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='code',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقدي'), ('BANK', 'تحويل بنكي'), ('CHEQUE', 'شيك'), ('CARD', 'بطاقة ائتمان'), ('ONLINE', 'دفع إلكتروني')], db_index=True, default='CASH', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('ايرادات اساسية', 'إيرادات أساسية'), ('ايرادات اخرى', 'إيرادات أخرى')], db_index=True, default='ايرادات اساسية', max_length=50, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='paymentout',
            name='code',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='paymentout',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.bank', verbose_name='البنك'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='code',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
    ]
