# Generated by Django 6.0.3 on 2026-05-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_billbuy_bill_buy_type_alter_billbuy_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='الرابط'),
        ),
    ]
