# Generated by Django 6.0.3 on 2026-05-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='الرابط'),
        ),
    ]
