# Generated by Django 6.0.3 on 2026-07-16 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_branch_offer_template'),
        ('courses', '0008_master_hours_master_offer_type'),
        ('students', '0008_alter_student_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='الرابط المختصر')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال')),
                ('workplace', models.CharField(blank=True, max_length=255, verbose_name='جهة العمل')),
                ('ministry', models.CharField(blank=True, max_length=255, verbose_name='الوزارة / المؤسسة')),
                ('governorate', models.CharField(blank=True, max_length=255, verbose_name='المحافظة')),
                ('communication_method', models.CharField(choices=[('phone', 'تلفون'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني'), ('visit', 'زيارة'), ('other', 'أخرى')], default='phone', max_length=20, verbose_name='وسيلة التواصل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('contact_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التواصل')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('no_answer', 'لم يتم الرد'), ('not_interested', 'غير مهتم'), ('interested', 'مهتم')], db_index=True, default='new', max_length=20, verbose_name='حالة التواصل')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحويل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospects', to='core.branch', verbose_name='الفرع')),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects_contacted', to=settings.AUTH_USER_MODEL, verbose_name='الموظف الذي قام بالتواصل')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects_converted', to=settings.AUTH_USER_MODEL, verbose_name='المحول إلى طالب')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='courses.master', verbose_name='التخصص')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospect', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'مستفسر',
                'verbose_name_plural': 'المستفسرون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='الرابط المختصر')),
                ('title', models.CharField(max_length=255, verbose_name='اسم العرض أو البرنامج')),
                ('content', models.TextField(blank=True, verbose_name='محتوى العرض')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ إرسال العرض')),
                ('status', models.CharField(choices=[('waiting', 'بانتظار الرد'), ('accepted', 'تم قبول العرض'), ('rejected', 'تم رفض العرض')], db_index=True, default='waiting', max_length=20, verbose_name='حالة العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospect_offers', to='core.branch', verbose_name='الفرع')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_offers', to='courses.course', verbose_name='الدورة')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='prospects.prospect', verbose_name='المستفسر')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_prospect_offers', to=settings.AUTH_USER_MODEL, verbose_name='الموظف الذي أرسل العرض')),
            ],
            options={
                'verbose_name': 'عرض مستفسر',
                'verbose_name_plural': 'عروض المستفسرين',
                'ordering': ['-sent_at'],
            },
        ),
    ]
