# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_account_slug'),
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('no_answer', 'لم يتم الرد'), ('not_interested', 'غير مهتم'), ('interested', 'مهتم'), ('registered', 'مسجل'), ('paid', 'مدفوع')], db_index=True, default='new', max_length=20, verbose_name='حالة التواصل'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='registrations.account', verbose_name='التسجيل'),
        ),
    ]
