# Generated by Django 6.0.3 on 2026-04-04 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفريق')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الفريق')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فريق',
                'verbose_name_plural': 'فرق العمل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الأول')),
                ('second_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الثاني')),
                ('third_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الثالث')),
                ('forth_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الرابع')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='المحمول')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='التليفون')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('photo', models.TextField(blank=True, verbose_name='الصورة (Base64)')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدير نظام')),
                ('last_login_date', models.DateTimeField(blank=True, null=True, verbose_name='آخر دخول')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='الإعدادات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='core.branch', verbose_name='الفرع الرئيسي')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.team', verbose_name='الفريق')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='core.branch', verbose_name='الفرع')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accesses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صلاحية فرع',
                'verbose_name_plural': 'صلاحيات الفروع',
                'unique_together': {('person', 'branch')},
            },
        ),
    ]
