# Generated by Django 6.0.3 on 2026-04-05 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('مدير_فرع', 'مدير فرع'), ('موظف_عروض', 'موظف عروض'), ('موظف_متابعة', 'موظف متابعة'), ('مدير_نظام', 'مدير نظام')], max_length=50, unique=True, verbose_name='الدور')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='الصلاحيات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
            },
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('offers_sent', models.PositiveIntegerField(default=0, verbose_name='العروض المرسلة')),
                ('offers_opened', models.PositiveIntegerField(default=0, verbose_name='العروض المفتوحة')),
                ('offers_interacted', models.PositiveIntegerField(default=0, verbose_name='التفاعلات')),
                ('subscriptions', models.PositiveIntegerField(default=0, verbose_name='الاشتراكات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.branch', verbose_name='الفرع')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'أداء موظف',
                'verbose_name_plural': 'أداء الموظفين',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('person', 'branch', 'period_month', 'period_year')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='core.branch', verbose_name='الفرع')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.role', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'دور موظف',
                'verbose_name_plural': 'أدوار الموظفين',
                'unique_together': {('person', 'role', 'branch')},
            },
        ),
    ]
