# Generated by Django 6.0.3 on 2026-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_employeeperformance_employeerole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='person',
            name='forth_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='الاسم الرابع'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False, verbose_name='موظف'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='المحمول'),
        ),
    ]
