# Generated by Django 6.0.3 on 2026-05-10 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_person_email_alter_person_first_name_and_more'),
        ('core', '0009_mastercategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='الرابط المختصر'),
        ),
    ]
