# Generated by Django 6.0.3 on 2026-05-10 10:00

from django.db import migrations
from django.utils.text import slugify


def fill_team_slugs(apps, schema_editor):
    Team = apps.get_model('accounts', 'Team')
    for team in Team.objects.all():
        if not team.slug:
            base = slugify(team.name, allow_unicode=True)
            slug = base
            counter = 1
            while Team.objects.filter(slug=slug).exclude(pk=team.pk).exists():
                slug = f"{base}-{counter}"
                counter += 1
            team.slug = slug
            team.save(update_fields=['slug'])


def reverse_fill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team_branch_team_slug'),
    ]

    operations = [
        migrations.RunPython(fill_team_slugs, reverse_fill),
    ]
