# Generated by Django 6.0.3 on 2026-05-10 12:00

from django.db import migrations
from django.utils.text import slugify


def fill_person_slugs(apps, schema_editor):
    Person = apps.get_model('accounts', 'Person')
    for person in Person.objects.all():
        if not person.slug:
            full_name = ' '.join(filter(None, [person.first_name, person.second_name, person.third_name, person.forth_name])).strip()
            base = slugify(full_name or person.email.split('@')[0], allow_unicode=True)
            slug = base
            counter = 1
            while Person.objects.filter(slug=slug).exclude(pk=person.pk).exists():
                slug = f"{base}-{counter}"
                counter += 1
            person.slug = slug
            person.save(update_fields=['slug'])


def reverse_fill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_person_slug'),
    ]

    operations = [
        migrations.RunPython(fill_person_slugs, reverse_fill),
    ]
