# Generated by Django 6.0.3 on 2026-05-10 13:00

from django.db import migrations
from django.utils.text import slugify


def fill_role_slugs(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    # choices from the historical model field
    choices = Role._meta.get_field('name').choices or []
    choice_map = dict(choices)
    for role in Role.objects.all():
        if not role.slug:
            name_display = choice_map.get(role.name, role.name)
            base = slugify(name_display, allow_unicode=True)
            slug = base
            counter = 1
            while Role.objects.filter(slug=slug).exclude(pk=role.pk).exists():
                slug = f"{base}-{counter}"
                counter += 1
            role.slug = slug
            role.save(update_fields=['slug'])


def reverse_fill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_role_slug'),
    ]

    operations = [
        migrations.RunPython(fill_role_slugs, reverse_fill),
    ]
