# Generated by Django 6.0.3 on 2026-05-10 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_fill_role_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerole',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('app_label', models.CharField(max_length=100, verbose_name='التطبيق')),
                ('model_name', models.CharField(max_length=100, verbose_name='الموديل')),
                ('action', models.CharField(choices=[('view', 'عرض'), ('add', 'إضافة'), ('change', 'تعديل'), ('delete', 'حذف')], max_length=20, verbose_name='الإجراء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'صلاحية',
                'verbose_name_plural': 'الصلاحيات',
                'ordering': ['app_label', 'model_name', 'action'],
                'unique_together': {('app_label', 'model_name', 'action')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='accounts.permission', verbose_name='الصلاحيات'),
        ),
    ]
