# Generated by Django 6.0.3 on 2026-05-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_employeerole_person_remove_role_permissions_and_more'),
        ('core', '0009_mastercategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='default_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_teams', to='core.branch', verbose_name='الفرع الافتراضي'),
        ),
        migrations.AddField(
            model_name='team',
            name='default_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_teams', to='accounts.role', verbose_name='الدور الافتراضي'),
        ),
    ]
