# Generated by Django 6.0.3 on 2026-05-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='signature',
            field=models.ImageField(blank=True, upload_to='person_signatures/', verbose_name='التوقيع'),
        ),
    ]
