# Generated by Django 6.0.3 on 2026-05-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_person_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='signature',
        ),
    ]
