# Generated by Django 6.0.3 on 2026-05-31 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_person_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='branch',
        ),
    ]
