# Generated by Django 6.0.3 on 2026-04-05 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('courses', '0002_course_target_level'),
        ('students', '0002_student_level_student_preferred_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان العرض')),
                ('content', models.TextField(verbose_name='محتوى العرض')),
                ('target_level', models.CharField(choices=[('مبتدئ', 'مبتدئ'), ('متوسط', 'متوسط'), ('متقدم', 'متقدم'), ('الكل', 'جميع المستويات')], default='الكل', max_length=20, verbose_name='المستوى المستهدف')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الإرسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال الفعلي')),
                ('status', models.CharField(choices=[('مسودة', 'مسودة'), ('مجدولة', 'مجدولة'), ('مرسلة', 'مرسلة'), ('منتهية', 'منتهية')], default='مسودة', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.branch', verbose_name='الفرع')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='courses.course', verbose_name='الدورة')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_offers', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'عرض طالب',
                'verbose_name_plural': 'عروض الطلاب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField(verbose_name='الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_notes', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='offers.studentoffer', verbose_name='العرض')),
            ],
            options={
                'verbose_name': 'ملاحظة عرض',
                'verbose_name_plural': 'ملاحظات العروض',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'البريد الإلكتروني'), ('whatsapp', 'واتساب'), ('app', 'إشعار التطبيق')], max_length=20, verbose_name='قناة الإرسال')),
                ('status', models.CharField(choices=[('مرسل', 'مرسل'), ('مقروء', 'مقروء'), ('تفاعل', 'تم التفاعل'), ('اشترك', 'تم الاشتراك'), ('لم_يتفاعل', 'لم يتفاعل')], default='مرسل', max_length=20, verbose_name='حالة التفاعل')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الفتح')),
                ('interacted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التفاعل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_recipients', to='students.student', verbose_name='الطالب')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='offers.studentoffer', verbose_name='العرض')),
            ],
            options={
                'verbose_name': 'مستلم عرض',
                'verbose_name_plural': 'مستلمو العروض',
                'ordering': ['-sent_at'],
                'unique_together': {('offer', 'student', 'channel')},
            },
        ),
    ]
