# Generated by Django 6.0.3 on 2026-05-07 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bank_branch_alter_branch_company'),
        ('offers', '0001_initial'),
        ('students', '0003_alter_contact_first_name_alter_contact_forth_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrecipient',
            name='channel',
            field=models.CharField(choices=[('email', 'البريد الإلكتروني'), ('whatsapp', 'واتساب'), ('app', 'إشعار التطبيق')], db_index=True, max_length=20, verbose_name='قناة الإرسال'),
        ),
        migrations.AlterField(
            model_name='offerrecipient',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='offers.studentoffer', verbose_name='العرض'),
        ),
        migrations.AlterField(
            model_name='offerrecipient',
            name='status',
            field=models.CharField(choices=[('مرسل', 'مرسل'), ('مقروء', 'مقروء'), ('تفاعل', 'تم التفاعل'), ('اشترك', 'تم الاشتراك'), ('لم_يتفاعل', 'لم يتفاعل')], db_index=True, default='مرسل', max_length=20, verbose_name='حالة التفاعل'),
        ),
        migrations.AlterField(
            model_name='offerrecipient',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_recipients', to='students.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='studentoffer',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='studentoffer',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='موعد الإرسال'),
        ),
        migrations.AlterField(
            model_name='studentoffer',
            name='sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاريخ الإرسال الفعلي'),
        ),
        migrations.AlterField(
            model_name='studentoffer',
            name='status',
            field=models.CharField(choices=[('مسودة', 'مسودة'), ('مجدولة', 'مجدولة'), ('مرسلة', 'مرسلة'), ('منتهية', 'منتهية')], db_index=True, default='مسودة', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='studentoffer',
            name='target_level',
            field=models.CharField(choices=[('مبتدئ', 'مبتدئ'), ('متوسط', 'متوسط'), ('متقدم', 'متقدم'), ('الكل', 'جميع المستويات')], db_index=True, default='الكل', max_length=20, verbose_name='المستوى المستهدف'),
        ),
    ]
