# Generated by Django 6.0.3 on 2026-05-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offerrecipient_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentoffer',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='الرابط'),
        ),
    ]
