# Generated by Django 6.0.3 on 2026-05-21 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_studentoffer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrecipient',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='offers.studentoffer', verbose_name='العرض'),
        ),
    ]
