# Generated by Django 6.0.3 on 2026-05-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offerrecipient_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentoffer',
            name='target_level',
        ),
    ]
