# Generated by Django 6.0.3 on 2026-05-21 11:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_remove_studentoffer_target_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentoffer',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العرض'),
        ),
        migrations.AddField(
            model_name='studentoffer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='السعر'),
        ),
        migrations.AddField(
            model_name='studentoffer',
            name='price_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='وصف السعر'),
        ),
        migrations.AddField(
            model_name='studentoffer',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية العرض'),
        ),
    ]
