# Generated by Django 6.0.3 on 2026-05-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_studentoffer_end_date_studentoffer_price_and_more'),
        ('students', '0006_alter_contact_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offerrecipient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='offerrecipient',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='بريد المستلم'),
        ),
        migrations.AddField(
            model_name='offerrecipient',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم المستلم'),
        ),
        migrations.AddField(
            model_name='offerrecipient',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='جوال المستلم'),
        ),
        migrations.AlterField(
            model_name='offerrecipient',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_recipients', to='students.student', verbose_name='الطالب'),
        ),
    ]
