# Generated by Django 6.0.3 on 2026-06-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_master_hours_master_offer_type'),
        ('offers', '0007_alter_offerrecipient_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentoffer',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_offers', to='courses.master', verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='studentoffer',
            name='title',
            field=models.CharField(max_length=255, verbose_name='نوع الاشتراك '),
        ),
    ]
