# Generated by Django 6.0.3 on 2026-06-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_studentoffer_master_alter_studentoffer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentoffer',
            name='manual_course_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد ساعات الدورة (يدوي)'),
        ),
        migrations.AddField(
            model_name='studentoffer',
            name='manual_course_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم الدورة (يدوي)'),
        ),
    ]
