# Generated by Django 6.0.3 on 2026-06-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_studentoffer_manual_course_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentoffer',
            name='manual_program_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد ساعات البرنامج (يدوي)'),
        ),
    ]
