# Generated by Django 6.0.3 on 2026-07-16 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_studentoffer_manual_program_hours'),
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrecipient',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_recipients', to='prospects.prospect', verbose_name='المستفسر'),
        ),
    ]
