# Generated by Django 6.0.3 on 2026-04-05 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('summary', 'ملخص عام'), ('offers', 'تقرير العروض'), ('branches', 'تقرير الفروع'), ('employees', 'تقرير الموظفين'), ('students', 'تقرير الطلاب')], max_length=20, verbose_name='نوع التقرير')),
                ('period', models.CharField(blank=True, max_length=50, verbose_name='الفترة')),
                ('data_json', models.JSONField(default=dict, verbose_name='بيانات التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.branch', verbose_name='الفرع')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
            },
        ),
    ]
