# Generated by Django 6.0.3 on 2026-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsnapshot',
            name='period',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='الفترة'),
        ),
        migrations.AlterField(
            model_name='reportsnapshot',
            name='report_type',
            field=models.CharField(choices=[('summary', 'ملخص عام'), ('offers', 'تقرير العروض'), ('branches', 'تقرير الفروع'), ('employees', 'تقرير الموظفين'), ('students', 'تقرير الطلاب')], db_index=True, max_length=20, verbose_name='نوع التقرير'),
        ),
    ]
