# Generated by Django 6.0.3 on 2026-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportsnapshot_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsnapshot',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='إلى تاريخ'),
        ),
        migrations.AddField(
            model_name='reportsnapshot',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='من تاريخ'),
        ),
    ]
