# Generated by Django 6.0.3 on 2026-05-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportsnapshot_end_date_reportsnapshot_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsnapshot',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='الرابط'),
        ),
    ]
