# Generated by Django 6.0.3 on 2026-04-04 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='الكود')),
                ('name', models.CharField(max_length=255, verbose_name='اسم التخصص')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='الفترة')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='core.branch', verbose_name='الفرع')),
                ('last_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل')),
                ('master_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters', to='core.mastercategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'التخصصات',
                'ordering': ['-created_at'],
                'unique_together': {('branch', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='الكود')),
                ('instructor', models.CharField(blank=True, max_length=255, verbose_name='المحاضر')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الشركة')),
                ('max_student_count', models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى للطلاب')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.master', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'دورة',
                'verbose_name_plural': 'الدورات',
                'ordering': ['-created_at'],
                'unique_together': {('master', 'code')},
            },
        ),
    ]
