# Generated by Django 6.0.3 on 2026-04-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='target_level',
            field=models.CharField(choices=[('مبتدئ', 'مبتدئ'), ('متوسط', 'متوسط'), ('متقدم', 'متقدم'), ('الكل', 'جميع المستويات')], default='الكل', max_length=20, verbose_name='المستوى المستهدف'),
        ),
    ]
