# Generated by Django 6.0.3 on 2026-05-07 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bank_branch_alter_branch_company'),
        ('courses', '0002_course_target_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.PositiveIntegerField(db_index=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='المحاضر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.master', verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_level',
            field=models.CharField(choices=[('مبتدئ', 'مبتدئ'), ('متوسط', 'متوسط'), ('متقدم', 'متقدم'), ('الكل', 'جميع المستويات')], db_index=True, default='الكل', max_length=20, verbose_name='المستوى المستهدف'),
        ),
        migrations.AlterField(
            model_name='master',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='master',
            name='code',
            field=models.PositiveIntegerField(db_index=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='اسم التخصص'),
        ),
    ]
