# Generated by Django 6.0.3 on 2026-05-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_code_alter_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='الرابط المختصر'),
        ),
    ]
