# Generated by Django 6.0.3 on 2026-06-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_master_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='master',
            name='code',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='الكود'),
        ),
    ]
