# Generated by Django 6.0.3 on 2026-06-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_code_alter_master_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='عدد الساعات'),
        ),
    ]
