# Generated by Django 6.0.3 on 2026-06-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='اسم الدورة'),
        ),
    ]
