# Generated by Django 6.0.3 on 2026-06-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='hours',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='عدد الساعات (للبرامج)'),
        ),
        migrations.AddField(
            model_name='master',
            name='offer_type',
            field=models.CharField(choices=[('program', 'برنامج / تخصص'), ('course', 'دورة منفردة')], db_index=True, default='program', max_length=20, verbose_name='نوع العرض'),
        ),
    ]
