# Generated by Django 6.0.3 on 2026-04-05 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('message_type', models.CharField(choices=[('استفسار', 'استفسار'), ('ملاحظة', 'ملاحظة'), ('طلب_دعم', 'طلب دعم'), ('عام', 'عام')], default='عام', max_length=20, verbose_name='نوع الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة داخلية',
                'verbose_name_plural': 'الرسائل الداخلية',
                'ordering': ['-created_at'],
            },
        ),
    ]
