# Generated by Django 6.0.3 on 2026-04-04 09:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوع مرفق',
                'verbose_name_plural': 'أنواع المرفقات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='الكود')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('course_payment_type', models.CharField(choices=[('نقدي', 'نقدي'), ('تقسيط', 'تقسيط'), ('آجل', 'آجل')], default='نقدي', max_length=20, verbose_name='نوع الدفع')),
                ('course_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الدورة')),
                ('course_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم')),
                ('course_profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نسبة الربح')),
                ('course_credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ الائتمان')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='courses.course', verbose_name='الدورة')),
                ('last_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AccountCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('fulfilled', models.BooleanField(default=False, verbose_name='تم الاستيفاء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_conditions', to='registrations.account', verbose_name='التسجيل')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_conditions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'شرط تسجيل',
                'verbose_name_plural': 'شروط التسجيلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_notes', to='registrations.account', verbose_name='التسجيل')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_notes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملاحظة تسجيل',
                'verbose_name_plural': 'ملاحظات التسجيلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('file_data', models.TextField(verbose_name='بيانات الملف (Base64)')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_type', models.CharField(max_length=100, verbose_name='نوع الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attaches', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('attach_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attaches', to='registrations.attachtype', verbose_name='نوع المرفق')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_attaches', to='registrations.account', verbose_name='التسجيل')),
                ('attach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_attaches', to='registrations.attach', verbose_name='المرفق')),
            ],
            options={
                'verbose_name': 'مرفق تسجيل',
                'verbose_name_plural': 'مرفقات التسجيلات',
                'ordering': ['-created_at'],
            },
        ),
    ]
