# Generated by Django 6.0.3 on 2026-05-07 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_code_alter_course_instructor_and_more'),
        ('registrations', '0001_initial'),
        ('students', '0003_alter_contact_first_name_alter_contact_forth_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.PositiveIntegerField(db_index=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='account',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='courses.course', verbose_name='الدورة'),
        ),
        migrations.AlterField(
            model_name='account',
            name='course_payment_type',
            field=models.CharField(choices=[('نقدي', 'نقدي'), ('تقسيط', 'تقسيط'), ('آجل', 'آجل')], db_index=True, default='نقدي', max_length=20, verbose_name='نوع الدفع'),
        ),
        migrations.AlterField(
            model_name='account',
            name='register_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='account',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='students.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='attach',
            name='attach_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attaches', to='registrations.attachtype', verbose_name='نوع المرفق'),
        ),
        migrations.AlterField(
            model_name='attachtype',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='attachtype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='الاسم'),
        ),
    ]
