# Generated by Django 6.0.3 on 2026-05-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_account_code_alter_account_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='الرابط'),
        ),
    ]
