# Generated by Django 6.0.3 on 2026-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مقروء'),
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='notification_type',
            field=models.CharField(choices=[('عرض_جديد', 'عرض جديد'), ('رسالة', 'رسالة'), ('تقرير', 'تقرير'), ('تنبيه', 'تنبيه')], db_index=True, max_length=20, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='appnotification',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='العنوان'),
        ),
    ]
